f=open("fh.txt","r")
print(f.read())
print(f.readline())
f=open("fh.txt","a")
f.write("this is writing")
f.close()
f=open("fh.txt","r")
print(f.read())
f = open("fh.txt", "r+")
print(f.read())
f = open("fh.txt", "w+")
f.truncate()
f = open("fh.txt", "r+")
print(f.read())